algoritmo "Aluno_Aprovado_Reprovado"
var
N1, N2, media, aprovado, reprovado: Real
inicio
        Escreval ("___ESCOLA BEABABEBU___")
        Escreva ("Primeira nota: ")
        Leia(N1)
        Escreva ("Segunda nota: ")
        Leia(N2)
        media <- N1 + N2 / 2
          Se (media > 7) entao
              Escreva ("ALUNO APROVADO")
          Senao
               Escreva ("ALUNO REPROVADO")
          FimSe




fimalgoritmo
